### ISSUE TITLE
Unable to post new user into database.

### ISSUE THREAD

**Issue by michellele994** [michellele994/LettuceEat#10]
Perla and I will be looking into this. 
Picture if from browsing console
![delete](https://user-images.githubusercontent.com/31457713/38333563-d58160aa-380d-11e8-83cd-196e4d1556c0.PNG)

**Comment by perlaballesteros** [comment]
we have a server file in the client, i did not earased that but i commented out the code. that might help, make sure you run yarn build in your main directory.

**Comment by michellele994** [comment]
Not exactly sure what happened, it may have been that I have added some code somewhere that made it break. I was able to revert back to what you have and now it is working. I made some variable name changes in my next pull request just to make it pretty, but it is still working.
